export const FETCH_LOCATION_FIND_START = 'FETCH_LOCATION_FIND_START';
export const FETCH_LOCATION_FIND_SUCCESS = 'FETCH_LOCATION_FIND_SUCCESS';
export const FETCH_LOCATION_FIND_FAILURE = 'FETCH_LOCATION_FIND_FAILURE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELL_FROM_FAVORITES = 'DELL_FROM_FAVORITES';

export const SWITCH_SCREEN_SEARCH = 'SWITCH_SCREEN_SEARCH';
export const SWITCH_SCREEN_FAVORITES = 'SWITCH_SCREEN_FAVORITES';
export const SWITCH_SCREEN_FORECAST = 'SWITCH_SCREEN_FORECAST';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

export const FETCH_WEATHER_CURRENT_LOCATION_START = 'FETCH_WEATHER_CURRENT_LOCATION_START';
export const FETCH_WEATHER_CURRENT_LOCATION_SUCCESS = 'FETCH_WEATHER_CURRENT_LOCATION_SUCCESS';
export const FETCH_WEATHER_CURRENT_LOCATION_FAILURE = 'FETCH_LOCATION_FIND_FAILURE';